[project]
name = "cdk-ops-sample"
version = "0.1.0"
description = "cdk pytest sample"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "boto3>=1.38.41",
    "moto[all]>=5.1.6",
    "pytest>=8.4.1",
    "pytest-cov>=6.2.1",
    "pytest-mock>=3.14.1",
]
